-- MySQL Script generated by MySQL Workbench
-- Thu Apr 26 20:16:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema surtidor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema surtidor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `surtidor` DEFAULT CHARACTER SET latin1 ;
USE `surtidor` ;

-- -----------------------------------------------------
-- Table `surtidor`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`cliente` (
  `CL_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CL_CI` DECIMAL(8,0) NOT NULL,
  `CL_fechainicio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CL_numerocompras` INT(11) NOT NULL,
  `CL_fechaultimacompra` TIMESTAMP NULL DEFAULT NULL,
  `CL_direccion` VARCHAR(60) NULL DEFAULT NULL,
  `CL_numerotelefono` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`CL_ID`, `CL_CI`),
  UNIQUE INDEX `CL_CI_UNIQUE` (`CL_CI` ASC),
  UNIQUE INDEX `CL_numerotelefono_UNIQUE` (`CL_numerotelefono` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`sucursal` (
  `SU_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `SU_Numerofiscal` DECIMAL(8,0) NOT NULL,
  `SU_direccion` TEXT NOT NULL,
  `SU_inicio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `SU_cupoempleados` DECIMAL(4,0) NOT NULL,
  `SU_empleados` DECIMAL(4,0) NOT NULL,
  PRIMARY KEY (`SU_ID`),
  UNIQUE INDEX `SU_ID_UNIQUE` (`SU_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`clienteregular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`clienteregular` (
  `CL_ID` INT(11) NOT NULL,
  `CL_CI` DECIMAL(8,0) NOT NULL,
  `SUCURSAL_SU_ID` INT(11) NOT NULL,
  PRIMARY KEY (`CL_ID`, `CL_CI`, `SUCURSAL_SU_ID`),
  INDEX `fk_Clientesregular_CLIENTE1_idx` (`CL_ID` ASC, `CL_CI` ASC),
  INDEX `fk_Clientesregular_SUCURSAL1_idx` (`SUCURSAL_SU_ID` ASC),
  CONSTRAINT `fk_Clientesregular_CLIENTE1`
    FOREIGN KEY (`CL_ID` , `CL_CI`)
    REFERENCES `surtidor`.`cliente` (`CL_ID` , `CL_CI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientesregular_SUCURSAL1`
    FOREIGN KEY (`SUCURSAL_SU_ID`)
    REFERENCES `surtidor`.`sucursal` (`SU_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`usuarioweb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`usuarioweb` (
  `CLWEB_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CLWEB_correo` VARCHAR(30) NOT NULL,
  `CLWEB_contraseña` VARCHAR(20) NOT NULL,
  `CLWEB_inicio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CLWEB_direccion` TEXT NOT NULL,
  `CLWEB_telefono` DECIMAL(11,0) NOT NULL,
  `CLWEB_nombre` VARCHAR(40) NOT NULL,
  `CLWEB_CI` DECIMAL(8,0) NOT NULL,
  `CL_ID` INT(11) NOT NULL,
  `CL_CI` DECIMAL(8,0) NOT NULL,
  PRIMARY KEY (`CLWEB_ID`),
  UNIQUE INDEX `CLWEB_correo_UNIQUE` (`CLWEB_correo` ASC),
  UNIQUE INDEX `CLWEB_telefono_UNIQUE` (`CLWEB_telefono` ASC),
  UNIQUE INDEX `CLWEB_contraseña_UNIQUE` (`CLWEB_contraseña` ASC),
  UNIQUE INDEX `CLWEB_CI_UNIQUE` (`CLWEB_CI` ASC),
  INDEX `fk_USUARIOWEB_CLIENTE1_idx` (`CL_ID` ASC, `CL_CI` ASC),
  CONSTRAINT `fk_USUARIOWEB_CLIENTE1`
    FOREIGN KEY (`CL_ID` , `CL_CI`)
    REFERENCES `surtidor`.`cliente` (`CL_ID` , `CL_CI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`puntuacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`puntuacion` (
  `PU_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PU_valoracion` INT(11) NOT NULL,
  `CLWEB_ID` INT(11) NOT NULL,
  PRIMARY KEY (`PU_ID`),
  UNIQUE INDEX `idPuntuacion_UNIQUE` (`PU_ID` ASC),
  INDEX `fk_PUNTUACION_USUARIOWEB1_idx` (`CLWEB_ID` ASC),
  CONSTRAINT `fk_PUNTUACION_USUARIOWEB1`
    FOREIGN KEY (`CLWEB_ID`)
    REFERENCES `surtidor`.`usuarioweb` (`CLWEB_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`comentario` (
  `CO_ID` INT(11) NOT NULL,
  `CO_contenido` TEXT NOT NULL,
  `PU_ID` INT(11) NOT NULL,
  PRIMARY KEY (`CO_ID`, `PU_ID`),
  INDEX `fk_COMENTARIO_PUNTUACION1_idx` (`PU_ID` ASC),
  CONSTRAINT `fk_COMENTARIO_PUNTUACION1`
    FOREIGN KEY (`PU_ID`)
    REFERENCES `surtidor`.`puntuacion` (`PU_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`metododepago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`metododepago` (
  `MT_ID` INT(11) NOT NULL,
  `MT_monto` INT(11) NOT NULL,
  `MT_fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`MT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`mododepago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`mododepago` (
  `MP_ID` INT(11) NOT NULL,
  `MP_hora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MP_Moneda` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`MP_ID`),
  UNIQUE INDEX `MP_ID_UNIQUE` (`MP_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`vendedor` (
  `VE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `VE_CI` INT(11) NOT NULL,
  `VE_SS` VARCHAR(20) NOT NULL,
  `VE_nombre` VARCHAR(60) NOT NULL,
  `VE_telefono` VARCHAR(45) NOT NULL,
  `VE_direccion` TEXT NOT NULL,
  `VE_fechainicio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `VE_numeroemergencia` DECIMAL(11,0) NOT NULL,
  `VE_sexo` VARCHAR(9) NOT NULL,
  `VE_horario` VARCHAR(25) NOT NULL,
  `SU_ID` INT(11) NOT NULL,
  PRIMARY KEY (`VE_ID`, `SU_ID`),
  UNIQUE INDEX `VE_CI_UNIQUE` (`VE_CI` ASC),
  UNIQUE INDEX `VE_SS_UNIQUE` (`VE_SS` ASC),
  UNIQUE INDEX `VE_ID_UNIQUE` (`VE_ID` ASC),
  INDEX `fk_Vendedor_SUCURSAL1_idx` (`SU_ID` ASC),
  CONSTRAINT `fk_Vendedor_SUCURSAL1`
    FOREIGN KEY (`SU_ID`)
    REFERENCES `surtidor`.`sucursal` (`SU_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`factura` (
  `FA_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FA_precioneto` FLOAT NOT NULL,
  `FA_IVA` FLOAT NOT NULL,
  `FA_preciototal` FLOAT NOT NULL,
  `FA_hora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FA_NItem` INT(11) NOT NULL,
  `CL_ID` INT(11) NOT NULL,
  `CL_CI` DECIMAL(8,0) NOT NULL,
  `VE_ID` INT(11) NOT NULL,
  `SU_ID` INT(11) NOT NULL,
  `MT_ID` INT(11) NOT NULL,
  `MP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`FA_ID`, `CL_ID`, `CL_CI`, `VE_ID`, `SU_ID`, `MT_ID`, `MP_ID`),
  UNIQUE INDEX `idFactura_UNIQUE` (`FA_ID` ASC),
  INDEX `fk_FACTURA_CLIENTE1_idx` (`CL_ID` ASC, `CL_CI` ASC),
  INDEX `fk_FACTURA_Vendedor1_idx` (`VE_ID` ASC),
  INDEX `fk_FACTURA_SUCURSAL1_idx` (`SU_ID` ASC),
  INDEX `fk_FACTURA_METODODEPAGO1_idx` (`MT_ID` ASC),
  INDEX `fk_FACTURA_MODODEPAGO1_idx` (`MP_ID` ASC),
  CONSTRAINT `fk_FACTURA_CLIENTE1`
    FOREIGN KEY (`CL_ID` , `CL_CI`)
    REFERENCES `surtidor`.`cliente` (`CL_ID` , `CL_CI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURA_METODODEPAGO1`
    FOREIGN KEY (`MT_ID`)
    REFERENCES `surtidor`.`metododepago` (`MT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURA_MODODEPAGO1`
    FOREIGN KEY (`MP_ID`)
    REFERENCES `surtidor`.`mododepago` (`MP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURA_SUCURSAL1`
    FOREIGN KEY (`SU_ID`)
    REFERENCES `surtidor`.`sucursal` (`SU_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURA_Vendedor1`
    FOREIGN KEY (`VE_ID`)
    REFERENCES `surtidor`.`vendedor` (`VE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`producto` (
  `PR_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PR_referencia` INT NOT NULL,
  `PR_talla` VARCHAR(10) NOT NULL,
  `PR_color` VARCHAR(30) NOT NULL,
  `PR_categoria` VARCHAR(20) NOT NULL,
  `PR_cantidad` INT(11) NOT NULL,
  `PR_precio` FLOAT NOT NULL,
  `PR_marca` VARCHAR(60) NOT NULL,
  `PR_descripcion` VARCHAR(60) NOT NULL,
  `PR_material` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`PR_ID`, `PR_referencia`),
  UNIQUE INDEX `PR_ID_UNIQUE` (`PR_ID` ASC),
  UNIQUE INDEX `productocol_UNIQUE` (`PR_referencia` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`descripcionfactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`descripcionfactura` (
  `PR_ID` INT(11) NOT NULL,
  `FA_ID` INT(11) NOT NULL,
  `CL_ID` INT(11) NOT NULL,
  `CL_CI` DECIMAL(8,0) NOT NULL,
  `VE_ID` INT(11) NOT NULL,
  `SU_ID` INT(11) NOT NULL,
  `MT_ID` INT(11) NOT NULL,
  `MP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`PR_ID`, `FA_ID`, `CL_ID`, `CL_CI`, `VE_ID`, `SU_ID`, `MT_ID`, `MP_ID`),
  INDEX `fk_DescripcionFactura_FACTURA1_idx` (`FA_ID` ASC, `CL_ID` ASC, `CL_CI` ASC, `VE_ID` ASC, `SU_ID` ASC, `MT_ID` ASC, `MP_ID` ASC),
  CONSTRAINT `fk_DescripcionFactura_FACTURA1`
    FOREIGN KEY (`FA_ID` , `CL_ID` , `CL_CI` , `VE_ID` , `SU_ID` , `MT_ID` , `MP_ID`)
    REFERENCES `surtidor`.`factura` (`FA_ID` , `CL_ID` , `CL_CI` , `VE_ID` , `SU_ID` , `MT_ID` , `MP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DescripcionFactura_PRODUCTO1`
    FOREIGN KEY (`PR_ID`)
    REFERENCES `surtidor`.`producto` (`PR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`historial` (
  `HI_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `HI_fecha` DATETIME NULL DEFAULT NULL,
  `HI_evento` TINYTEXT NULL DEFAULT NULL,
  `HI_usuario` VARCHAR(20) NULL DEFAULT NULL,
  `REF` VARCHAR(10) NULL DEFAULT NULL,
  `VIEJO_NOM_ART` VARCHAR(50) NULL DEFAULT NULL,
  `NUEVO_NOM_ART` VARCHAR(50) NULL DEFAULT NULL,
  `VIEJO_SUCURSAL` VARCHAR(50) NULL DEFAULT NULL,
  `NUEVO_SUCURSAL` VARCHAR(50) NULL DEFAULT NULL,
  `VIEJO_USER` TINYTEXT NULL DEFAULT NULL,
  `NUEVO_USER` TINYTEXT NULL DEFAULT NULL,
  `VIEJO_CAT` VARCHAR(50) NULL DEFAULT NULL,
  `NUEVO_CAT` VARCHAR(50) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `VIEJO_PRECIO` FLOAT NULL DEFAULT NULL,
  `NUEVO_PRECIO` FLOAT NULL DEFAULT NULL,
  `VIEJO_CANT` INT(20) NULL DEFAULT NULL,
  `NUEVO_CANT` INT(20) NULL DEFAULT NULL,
  `PR_ID` INT(11) NOT NULL,
  `PR_referencia` INT NOT NULL,
  PRIMARY KEY (`HI_ID`, `PR_ID`, `PR_referencia`),
  INDEX `fk_historial_producto1_idx` (`PR_ID` ASC, `PR_referencia` ASC),
  CONSTRAINT `fk_historial_producto1`
    FOREIGN KEY (`PR_ID` , `PR_referencia`)
    REFERENCES `surtidor`.`producto` (`PR_ID` , `PR_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `surtidor`.`inventariosucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`inventariosucursal` (
  `PR_ID` INT(11) NOT NULL,
  `SU_ID` INT(11) NOT NULL,
  PRIMARY KEY (`PR_ID`, `SU_ID`),
  INDEX `fk_INVENTARIOSUCURSAL_SUCURSAL1_idx` (`SU_ID` ASC),
  CONSTRAINT `fk_INVENTARIOSUCURSAL_PRODUCTO1`
    FOREIGN KEY (`PR_ID`)
    REFERENCES `surtidor`.`producto` (`PR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVENTARIOSUCURSAL_SUCURSAL1`
    FOREIGN KEY (`SU_ID`)
    REFERENCES `surtidor`.`sucursal` (`SU_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `surtidor`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surtidor`.`proveedor` (
  `PRV_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PRV_RM` INT(11) NOT NULL,
  `PRV_nombre` VARCHAR(60) NOT NULL,
  `PRV_producto` TEXT NOT NULL,
  `PRV_telefono` DECIMAL(11,0) NOT NULL,
  `PRV_correo` VARCHAR(40) NOT NULL,
  `PR_ID` INT(11) NOT NULL,
  PRIMARY KEY (`PRV_ID`, `PR_ID`),
  UNIQUE INDEX `PROVEEDORcol_UNIQUE` (`PRV_RM` ASC),
  UNIQUE INDEX `PRV_ID_UNIQUE` (`PRV_ID` ASC),
  UNIQUE INDEX `PRV_telefono_UNIQUE` (`PRV_telefono` ASC),
  UNIQUE INDEX `PRV_correo_UNIQUE` (`PRV_correo` ASC),
  INDEX `fk_PROVEEDOR_PRODUCTO_idx` (`PR_ID` ASC),
  CONSTRAINT `fk_PROVEEDOR_PRODUCTO`
    FOREIGN KEY (`PR_ID`)
    REFERENCES `surtidor`.`producto` (`PR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
